namespace: default

image:
  repository: 767415906716.dkr.ecr.us-east-1.amazonaws.com/lesson-5-ecr
  tag: v1.0.2
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8000

ingress:
  enabled: false

hpa:
  minReplicas: 2
  maxReplicas: 6
  averageUtilization: 70

replicaCount: 2
