namespace: default

image:
  repository: 767415906716.dkr.ecr.us-east-1.amazonaws.com/lesson-5-ecr
  tag: v1.0.11
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8000

ingress:
  enabled: false

config:
  POSTGRES_HOST: db
  POSTGRES_PORT: 5432
  POSTGRES_USER: django_user
  POSTGRES_DB: django_db
  POSTGRES_PASSWORD: pass9764gd

hpa:
  minReplicas: 2
  maxReplicas: 6
  averageUtilization: 70

replicaCount: 2
